### PR TITLE
Fix compilation under Sundials/ML 5.8.0

### PR DESCRIPTION
**Pull request by tbrk**
The interface to solvers changes in Sundials >= 4.0.0. For example, rather than initialize Cvode with `Functional` or `Newton`, one now passes an optional `~nlsolver` argument to specify a nonlinear solver. This pull request updates Zelus to compile with the upcoming release of Sundials/ML 5.8.0p0. It should be accepted once the new version of Sundials/ML hits opam.

### CODE REVIEW

**Comment by tbrk** [comment]
The failures are normal since the new version of Sundials/ML has not yet been released into opam.

**Comment by gbdrt** [comment]
Just updated the Github action (which "manually" installed sundials.3.2.1).

Hopefully a simple `opam install sundialsml` will install the sundials depext as well?
Otherwise you might need to add a `sudo apt-get install sundials` in `.github/workflows/build.yml` and `.github/workflows/opam.yml`.

**Comment by tbrk** [comment]
I don't know much about github actions. The `sundialsml` opam package depends on the `conf-sundials` opam package. On the opam-repository integration checks, which seem to be different to the standard github ones, the latter package causes the installation of the underlying sundials library (on several different distributions). My guess is that the tests will pass when the zelus package is submitted to opam-repository.

**Comment by tbrk** [comment]
[Apparently](https://opam.ocaml.org/doc/FAQ.html#Some-packages-fail-during-compilation-complaining-about-missing-dependencies-quot-m4-quot-quot-libgtk-quot-etc) `opam depext sundialsml` should install the external packages.

**Comment by gbdrt** [comment]
That should not be happening.
The action is just running `opam install sundialsml`.

Let me try with the new ocaml github action.

**Comment by gbdrt** [comment]
Still not working.
We use the default ocaml github action (https://github.com/ocaml/setup-ocaml) and by default `opam-depext` is set to true.
External dependencies should be automatically installed.

Here is the error log
```
[ERROR] The compilation of conf-sundials.2 failed at "cc -E test.c".
+ /home/runner/.opam/opam-init/hooks/sandbox.sh "build" "cc" "-E" "test.c" (CWD=/home/runner/work/zelus/zelus/_opam/.opam-switch/build/conf-sundials.2)
- test.c:1:10: fatal error: sundials/sundials_config.h: No such file or directory
-     1 | #include <sundials/sundials_config.h>
-       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
- compilation terminated.
- # 1 "test.c"
- # 1 "<built-in>"
- # 1 "<command-line>"
- # 31 "<command-line>"
- # 1 "/usr/include/stdc-predef.h" 1 3 4
- # 32 "<command-line>" 2
- # 1 "test.c"
- test.c:1:10: fatal error: sundials/sundials_config.h: No such file or directory
-     1 | #include <sundials/sundials_config.h>
-       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
- compilation terminated.
- # 1 "test.c"
- # 1 "<built-in>"
- # 1 "<command-line>"
- # 31 "<command-line>"
- # 1 "/usr/include/stdc-predef.h" 1 3 4
- # 32 "<command-line>" 2
- # 1 "test.c"
Processing  3/6:
Processing  4/6:
⬇ retrieved sundialsml.5.8.0p0  (https://github.com/inria-parkas/sundialsml/archive/refs/tags/v5.8.0p0.tar.gz)

#=== ERROR while compiling conf-sundials.2 ====================================#
# context     2.1.2 | linux/x86_64 | ocaml-base-compiler.4.13.1 | git+https://github.com/ocaml/opam-repository.git
# path        ~/work/zelus/zelus/_opam/.opam-switch/build/conf-sundials.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build cc -E test.c
# exit-code   1
# env-file    ~/.opam/log/conf-sundials-20025-ba22d3.env
# output-file ~/.opam/log/conf-sundials-20025-ba22d3.out
### output ###
# test.c:1:10: fatal error: sundials/sundials_config.h: No such file or directory


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions were aborted
│ ∗ install sundialsml 5.8.0p0
└─ 
┌─ The following actions failed
│ λ build conf-sundials 2
└─ 
╶─ No changes have been performed
# Run eval $(opam env) to update the current shell environment
#     1 | #include <sundials/sundials_config.h>
#       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
# compilation terminated.
# # 1 "test.c"
# # 1 "<built-in>"
# # 1 "<command-line>"
# # 31 "<command-line>"
# # 1 "/usr/include/stdc-predef.h" 1 3 4
# # 32 "<command-line>" 2
# # 1 "test.c"

'opam install -y sundialsml' failed.
Error: Process completed with exit code 31.
```

**Comment by gbdrt** [comment]
Note that automatic depext installation is working with this setup for gtk and lablgtk (see e.g., https://github.com/INRIA/zelus/runs/4532377178).

**Comment by gbdrt** [comment]
🚀

**Comment by tbrk** [comment]
> Note that automatic depext installation is working with this setup for gtk and lablgtk (see e.g., https://github.com/INRIA/zelus/runs/4532377178).

I'm only a beginner with these yaml files, but it seems to me that the critical line in the build script is:
```
sudo apt-get -y install gtk2.0
```
The later `opam install conf-gtk` only works correctly because the underlying package has already been installed.

It also seems to me that `opam-depext` does not automate the installation of the underlying packages (even though the documentation seems to suggest (a) that it does and (b) that this feature is now part of `opam install`). Thankfully, an explicit invocation does the job.

**Comment by tbrk** [comment]
Sadly, the CI environment only installs the packages for Sundials 3.1.2... It doesn't really matter, since Sundials/ML should work with any version from 2.7.0 onwards and Zélus only uses a basic subset of the available features.

**Comment by gbdrt** [comment]
> I'm only a beginner with these yaml files, but it seems to me that the critical line in the build script is:
> 
> ``
> sudo apt-get -y install gtk2.0
> ```
> 
> The later `opam install conf-gtk` only works correctly because the underlying package has already been installed.

I am not sure. I did remove these lines when I updated the action this morning.
And the current version that is running here (✅ ) does not contain these lines [see e.g. here](https://github.com/tbrk/zelus/blob/sundialsml-5.8.0/.github/workflows/build.yml).
We now install everything via opam.

> Sadly, the CI environment only installs the packages for Sundials 3.1.2... It doesn't really matter, since Sundials/ML should work with any version from 2.7.0 onwards and Zélus only uses a basic subset of the available features.

Is that sill true? We are no longer manually installing sundials from the archive.
I would have expected `opam depext` to install the latest version.

**Comment by gbdrt** [comment]
I still don't understand why this is not the default behaviour for this package, but it's great that you found a work around!

**Comment by tbrk** [comment]
OK, I have no idea then! Like you, just happy there is a workaround.
The `opam depext` installs the current version of the libraries for the given distro. The CI seems to be using ubuntu focal (20.04) and [thus](https://packages.ubuntu.com/focal/libsundials-dev) Sundials 3.1.2. It doesn't really matter because `conf-sundials` has been tested on a bunch of other distros prior to acceptance for `opam-repository`.

**Pull request merged**
